"""main table

Revision ID: 6c4087b2d29f
Revises: 4d8ac9861af1
Create Date: 2025-02-17 01:55:02.677509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4087b2d29f'
down_revision = '4d8ac9861af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('main-table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main-table',
    sa.Column('table_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('local_dict', sa.BLOB(), nullable=True),
    sa.Column('step_list', sa.BLOB(), nullable=True),
    sa.Column('main_list', sa.BLOB(), nullable=True),
    sa.Column('menu_list', sa.BLOB(), nullable=True),
    sa.Column('merge_list', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
