"""add main,menu,merge lists to MainTable

Revision ID: a024d11ac6f0
Revises: f7e3038683ad
Create Date: 2025-04-08 19:57:58.931968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a024d11ac6f0'
down_revision = 'f7e3038683ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sheet_table')
    op.drop_table('settings_table')
    op.drop_table('main_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('table_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sheet_id', sa.VARCHAR(), nullable=True),
    sa.Column('sheet_name', sa.VARCHAR(), nullable=True),
    sa.Column('wellcome_text', sa.VARCHAR(), nullable=True),
    sa.Column('wellcome_picture', sa.VARCHAR(), nullable=True),
    sa.Column('wellcome_picture_link', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('table_id', sa.VARCHAR(), nullable=True),
    sa.Column('sheet_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['main_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('local_dict', sa.BLOB(), nullable=True),
    sa.Column('step_list', sa.BLOB(), nullable=True),
    sa.Column('main_list', sa.BLOB(), nullable=True),
    sa.Column('menu_list', sa.BLOB(), nullable=True),
    sa.Column('merge_list', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
