"""main table

Revision ID: d3c8eff3d5bb
Revises: a562639743f6
Create Date: 2025-02-16 20:37:31.274037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c8eff3d5bb'
down_revision = 'a562639743f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main-table')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('local_dict', sa.BLOB(), nullable=True),
    sa.Column('step_list', sa.BLOB(), nullable=True),
    sa.Column('main_list', sa.BLOB(), nullable=True),
    sa.Column('menu_list', sa.BLOB(), nullable=True),
    sa.Column('merge_list', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('main-table',
    sa.Column('table_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('table_id')
    )
    # ### end Alembic commands ###
